## 文章
index:
  uri: "/"
  class: \clomery\main\response\IndexResponse
index-page:
  uri: "/page/{page:int}"
  class: \clomery\main\response\IndexResponse
article:
  uri: "/article/{article:string}"
  class: \clomery\main\response\ArticleResponse
article-search:
  uri: "/search"
  class: \clomery\main\response\IndexResponse
## 标签
tags:
  uri: "/tags"
  class: \clomery\main\response\TagResponse
article-tag:
  uri: "/tag/{tag:string}"
  class: \clomery\main\response\TagArticleResponse
article-tag-page:
  uri: "/tag/{tag:string}/page/{page:int}"
  class: \clomery\main\response\TagArticleResponse
## 分类
categorys:
  uri: "/categories"
  class: \clomery\main\response\CategoryResponse
article-category:
  uri: "/category/{category:string}"
  class: \clomery\main\response\CategoryArticleResponse
article-category-page:
  uri: "/category/{category:string}/page/{page:int}"
  class: \clomery\main\response\CategoryArticleResponse
## 归档
archives:
  uri: "/archives"
  class: \clomery\main\response\IndexResponse
article-archive:
  uri: "/archive/{date:string}"
  class: \clomery\main\response\IndexResponse
article-archive-page:
  uri: "/archive/{date:string}/page/{page:int}"
  class: \clomery\main\response\IndexResponse